# Generated by Django 5.2.1 on 2025-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='identification_number',
            field=models.IntegerField(unique=True),
        ),
    ]
