# Generated by Django 5.2.1 on 2025-06-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_candidates_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
