# Generated by Django 5.2.1 on 2025-07-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_candidates_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Masculino', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='grade',
            field=models.CharField(choices=[('11-1', '11-1'), ('11-2', '11-2'), ('11-3', '11-3'), ('11-4', '11-4'), ('11-5', '11-5')], default='11-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='position',
            field=models.CharField(choices=[('Personería', 'Personería'), ('Contraloría', 'Contraloría')], default='Personería', max_length=20),
        ),
    ]
